parameters:
#    parameter_name: value
services:
    app.menu_builder:
        class: Ebay\AdminBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]
    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@app.menu_builder", createMainMenu]
        arguments: ["@knp_menu.factory", []]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
          - { name: twig.extension }
    app.twig_extension:
        class: Ebay\AdminBundle\Twig\AsinExtension
        public: false
        tags: 
            - { name: twig.extension }